### ISSUE TITLE
create user nologin option

### ISSUE THREAD

**Issue by bitchecker** [suraganijanakiram/FTP_Manager#2]
hi,
i'm watching your project and i think that is a very helpful tool but, while i'm reading the code i've seen that the user is created with default options, so, he can log-in into the server.

what do you think about create an FTP group and add all ftp-users into this group with nologin default shell and an FTP home like `/home/ftp/` as root dir for all ftp users?

**Comment by suraganijanakiram** [comment]
hi 
First of all thanks for checking my work and providing your feedback. i am very happy for that :)

comming to your question i have kept server login intensionally since some times users must login and execute some commands or even check the application status etc.

we can restrict server login for some users.the below will update nologin shell for mentioned user.

1.lock user to login into server via ssh.
2.unlock user to login into server via ssh.

even though the user login into server he cant do anything with out sudo access(cant view,edit or delete files of other user).

we cant set a same home directory for different users.

what we can do is we can add /home/ftp and add the users to the group and give the group access to the directory.but there is a problem here since if A upload the file B can delete it and there will be no security.

i am closing the case since there is no issue in the code.

you are always welcome to post you thoughts here :) 

Thanks again
